name: Add Label

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Add bug label
        run: |
          curl -X POST \
            --url "https://api.github.com/repos/Claudia-M-A/gh-security/issues/4/labels" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"labels":["bug"]}' \
            --fail
